name: Build Packages

on:
  push:
    paths-ignore:
    - 'doc/**'
    - '**.md'
    - 'appveyor.yml'
    - '.travis.yml'
  pull_request:
    paths-ignore:
    - 'doc/**'
    - '**.md'
    - 'appveyor.yml'
    - '.travis.yml'

env:
  VERSION: 2024.2
  THUNDER_RELEASE: ${{ startsWith(github.ref, 'refs/tags/2') }}
  DEPS: git llvm17 libinotify openal-soft xorg 7-zip cmake ninja pkgconf ccache
  QT: qt5-widgets qt5-core qt5-gamepad qt5-gui qt5-svg qt5-xml qmake qt5 
  CC: clang17
  CXX: clang++17
  CCACHE_CFLAGS: -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
  CCACHE_DIR: ".ccache"
  CCACHE_COMPRESS: "true"
  CCACHE_COMPRESSLEVEL: "4"
  CCACHE_MAXSIZE: "1G"

jobs:
  freebsd:
    runs-on: ubuntu-latest
    name: FreeBSD CMake
    steps:
    - name: Prepare ccache timestamp
      id: ccache_cache_timestamp
      shell: bash
      run: |
        echo "timestamp=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
    - name: Build FreeBSD 14.1 Packages
      id: freebsd-14-1
      uses: vmactions/freebsd-vm@v1
      with:
        envs: '
          DEPS QT CC CXX
          CCACHE_FLAGS
          CCACHE_DIR
          CCACHE_COMPRESS
          CCACHE_COMPRESSLEVEL
          CCACHE_MAXSIZE
        '
        usesh: true
        sync: rsync
        release: "14.1"
        prepare: |
          pkg install -y $DEPS
          pkg install -y $QT
        run: |
          ccache -z
          git clone --recursive --depth 1 https://github.com/thunder-engine/thunder
          mkdir -pv tmp
          cd tmp
          CC=$CC CXX=$CXX cmake $CCACHE_FLAGS ../thunder -G "Ninja"
          ninja -j 1
          ninja install
          mkdir -pv release
          mv -v install-root release
          7z a -t7z ../ThunderEngine-freebsd-14.1-x86_64.7z release/install-root
          ccache -s
    - name: Upload Latest Thunder Release
      uses: actions/upload-artifact@v4
      with:
        name: ThunderEngine-freebsd-14.1-x86_64.7z
        path: ThunderEngine-freebsd-14.1-x86_64.7z
    - name: Cache FreeBSD 14.1 ccache files
      uses: actions/cache@v4
      with:
        envs: '
          CCACHE_DIR
        '
        path: "$CCACHE_DIR-bsd-14-1"
        key: FreeBSD-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}-${{ hashfiles('**') }}
    - name: Adjust Hostname FreeBSD 14.1
      id: adjust-hostname
      run:
        hostname freebsd-latest-complete
    - name: Build FreeBSD 14.0 Packages
      id: freebsd-14-0
      uses: vmactions/freebsd-vm@v1
      with:
        envs: '
          DEPS QT CC CXX
          CCACHE_FLAGS
          CCACHE_DIR
          CCACHE_COMPRESS
          CCACHE_COMPRESSLEVEL
          CCACHE_MAXSIZE
        '
        usesh: true
        sync: rsync
        release: "14.0"
        prepare: |
          pkg install -y $DEPS
          pkg install -y $QT
        run: |
          ccache -z
          git clone --recursive --depth 1 https://github.com/thunder-engine/thunder
          mkdir -pv tmp
          cd tmp
          CC=$CC CXX=$CXX cmake $CCACHE_FLAGS ../thunder -G "Ninja"
          ninja -j 1
          ninja install
          ccache -s
    - name: Adjust Hostname FreeBSD 14.0
      id: adjust-hostname-14-0
      run:
        hostname freebsd-14-0-complete
    - name: Cache FreeBSD 14.0 ccache files
      uses: actions/cache@v4
      with:
        envs: '
          CCACHE_DIR
        '
        path: "$CCACHE_DIR-bsd-14-0"
        key: FreeBSD-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}-${{ hashfiles('**') }}
    - name: Build FreeBSD 13.3 Packages
      id: freebsd-13-3
      uses: vmactions/freebsd-vm@v1
      with:
        envs: '
          DEPS QT CC CXX
          CCACHE_FLAGS
          CCACHE_DIR
          CCACHE_COMPRESS
          CCACHE_COMPRESSLEVEL
          CCACHE_MAXSIZE
        '
        usesh: true
        sync: rsync
        release: "13.3"
        prepare: |
          pkg install -y $DEPS
          pkg install -y $QT
        run: |
          ccache -z
          git clone --recursive --depth 1 https://github.com/thunder-engine/thunder
          mkdir -pv tmp
          cd tmp
          CC=$CC CXX=$CXX cmake $CCACHE_FLAGS ../thunder -G "Ninja"
          ninja -j 1
          ninja install
          ccache -s
    - name: Adjust Hostname FreeBSD 13.3
      id: adjust-hostname-13-3
      run:
        hostname freebsd-13-3-complete
    - name: Cache FreeBSD 13.3 ccache files
      uses: actions/cache@v4
      with:
        envs: '
          CCACHE_DIR
        '
        path: "$CCACHE_DIR-bsd-13-3"
        key: FreeBSD-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}-${{ hashfiles('**') }}
    - name: Build FreeBSD 13.2 Packages
      id: freebsd-13-2
      uses: vmactions/freebsd-vm@v1
      with:
        envs: '
          DEPS QT CC CXX
          CCACHE_FLAGS
          CCACHE_DIR
          CCACHE_COMPRESS
          CCACHE_COMPRESSLEVEL
          CCACHE_MAXSIZE
        '
        usesh: true
        sync: rsync
        release: "13.2"
        prepare: |
          pkg install -y $DEPS
          pkg install -y $QT
        run: |
          ccache -z
          git clone --recursive --depth 1 https://github.com/thunder-engine/thunder
          mkdir -pv tmp
          cd tmp
          CC=$CC CXX=$CXX cmake $CCACHE_FLAGS ../thunder -G "Ninja"
          ninja -j 1
          ninja install
          ccache -s
    - name: Cache FreeBSD 13.3 ccache files
      uses: actions/cache@v4
      with:
        envs: '
          CCACHE_DIR
        '
        path: "$CCACHE_DIR-bsd-13-2"
        key: FreeBSD-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}-${{ hashfiles('**') }}
